SET NOCOUNT ON;
GO

ALTER DATABASE CURRENT
SET CHANGE_TRACKING = ON
(
    CHANGE_RETENTION = 2 DAYS,
    AUTO_CLEANUP = ON
);
GO

ALTER TABLE [source].[MSTR_PROVEEDORES]
ENABLE CHANGE_TRACKING;
GO

ALTER TABLE [source].[MSTR_ARTICULOS]
ENABLE CHANGE_TRACKING;
GO

ALTER TABLE [source].[MSTR_TIENDAS]
ENABLE CHANGE_TRACKING;
GO

ALTER TABLE [source].[CRM_MIEMBROS]
ENABLE CHANGE_TRACKING;
GO

ALTER TABLE [source].[TRANS_VENTAS]
ENABLE CHANGE_TRACKING;
GO

ALTER TABLE [source].[INV_STOCK_DIARIO]
ENABLE CHANGE_TRACKING;
GO

ALTER TABLE [source].[POST_DEVOLUCIONES]
ENABLE CHANGE_TRACKING;
GO

PRINT 'Change Tracking habilitado correctamente.';
GO