SELECT 'MSTR_PROVEEDORES' AS tabla, COUNT(*) AS registros
    FROM [source].[MSTR_PROVEEDORES]

UNION ALL

SELECT 'MSTR_ARTICULOS', COUNT(*)
    FROM [source].[MSTR_ARTICULOS]

UNION ALL

SELECT 'MSTR_TIENDAS', COUNT(*)
    FROM [source].[MSTR_TIENDAS]

UNION ALL

SELECT 'CRM_MIEMBROS', COUNT(*)
    FROM [source].[CRM_MIEMBROS]

UNION ALL

SELECT 'TRANS_VENTAS', COUNT(*)
    FROM [source].[TRANS_VENTAS]

UNION ALL

SELECT 'INV_STOCK_DIARIO', COUNT(*)
    FROM [source].[INV_STOCK_DIARIO]

UNION ALL

SELECT 'POST_DEVOLUCIONES', COUNT(*)
    FROM [source].[POST_DEVOLUCIONES];